Update Dockerfile-priiiiyo-mirror-bot

diff --git a/Dockerfile-priiiiyo-mirror-bot b/Dockerfile-priiiiyo-mirror-bot
--- a/Dockerfile-priiiiyo-mirror-bot
+++ b/Dockerfile-priiiiyo-mirror-bot
@@ -1,40 +1,35 @@
-FROM python:3-slim-buster
+FROM ubuntu:20.04
 
-WORKDIR /usr/src/app
-RUN chmod 777 /usr/src/app
+RUN set -ex \
+    # Setup environment
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -qq update \
+    && apt-get -qq -y dist-upgrade \
+    && apt-get -qq -y install --no-install-recommends \
+        locales python3 python3-lxml python3-pip \
+        # MegaSDK-REST dependencies
+        libc-ares-dev libcrypto++-dev libcurl4-openssl-dev \
+        libmagic-dev libsodium-dev libsqlite3-dev libssl-dev \
+        # priiiiyo-mirror-bot dependencies
+        aria2 curl ffmpeg jq p7zip-full mediainfo p7zip-rar pv \
+    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
+    && locale-gen \
+    # Setup priiiiyo-mirror-bot dependencies
+    && curl -fsSL https://github.com/jaskaranSM/megasdkrest/releases/download/v0.1/megasdkrest -o /usr/local/bin/megasdkrest \
+    && chmod +x /usr/local/bin/megasdkrest \
+    && curl -fsSLO https://raw.githubusercontent.com/priiiiyo/priiiiyo-mirror-bot/master/requirements.txt \
+    && pip3 install --no-cache-dir -r requirements.txt \
+    && rm requirements.txt \
+    # Cleanup environment
+    && apt-get -qq -y autoremove --purge \
+    && apt-get -qq -y clean \
+    && rm -rf -- /var/lib/apt/lists/* /var/cache/apt/archives/* /etc/apt/sources.list.d/*
 
-RUN apt-get -qq update && \
-    apt-get install -y software-properties-common && \
-    rm -rf /var/lib/apt/lists/* && \
-    apt-add-repository non-free && \
-    apt-get -qq update && \
-    apt-get -qq install -y tzdata aria2 wget git python3 python3-pip \
-    locales python3-lxml \
-    curl pv jq ffmpeg \
-    p7zip-full mediainfo p7zip-rar \
-    libcrypto++-dev libssl-dev \
-    libc-ares-dev libcurl4-openssl-dev \
-    libsqlite3-dev libsodium-dev && \
-    apt-get purge -y software-properties-common \
-    curl -L https://github.com/jaskaranSM/megasdkrest/releases/download/v0.1/megasdkrest -o /usr/local/bin/megasdkrest && \
-    chmod +x /usr/local/bin/megasdkrest
+ENV DEBIAN_FRONTEND=noninteractive \
+    LANG=en_US.UTF-8 \
+    LANGUAGE=en_US:en \
+    LC_ALL=en_US.UTF-8
 
-COPY requirements.txt .
-COPY extract /usr/local/bin
-COPY pextract /usr/local/bin
-RUN chmod +x /usr/local/bin/extract && chmod +x /usr/local/bin/pextract
-RUN wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht.dat -O /usr/src/app/dht.dat && \
-wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat -O /usr/src/app/dht6.dat
-RUN pip3 install --no-cache-dir -r requirements.txt
-RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \ 
-locale-gen
-ENV LANG en_US.UTF-8
-ENV LANGUAGE en_US:en
-ENV LC_ALL en_US.UTF-8
+CMD ["bash", "start.sh"]
 
-COPY . .
-COPY netrc /root/.netrc
-RUN chmod 600 /usr/src/app/netrc
-RUN chmod +x aria.sh
-
-CMD ["bash","start.sh"]
+# vim: ft=dockerfile
